server:
  port: 9401

spring:
  application:
    name: turbine-server #服务唯一名字

eureka:
  client: #客户端注册进eureka服务列表内
    register-with-eureka: false    # false表示不向注册中心注册自己。
    service-url:
      defaultZone: http://eureka7201.com:7201/eureka  # 客户端注册进eureka服务集群列表内

#cluster-name-expression：指定集群的名称为default，当服务实例非常多的时候，可以启动多个Turbine来
                          #构建不同的聚合集群，而该参数可以区分这些不同的集群，同时该参数可以在
                         #Hystrix仪表盘中用来定位不同的聚合集群，只需在Hystrix Stream的URL中通过cluster参数来指定。


#combine-host-port: 当该参数未true时，可以让同一主机上的服务通过主机名与端口号
                    #的组合来进行区分，默认情况下会以host来区分不同的服务，这
                   #会使得在本地调试的时候，本机上不同服务聚合成一个服务来统计

turbine:
  app-config: weather-data-server              # 监控的应用名字
  cluster-name-expression: "'default'"    # 表示集群的名字为default
  combine-host-port: true               # 表示同一主机上的服务通过host和port的组合来进行区分


info:
  app.name: turbine-server-${server.port}-provider
  company.name: https://blog.csdn.net/yy290879584
  # 调试用
#  build.artifactId: ${project.artifactId}
#  build.version: ${project.version}
 # 打包用
  build.artifactId: $project.artifactId$
  build.version: $project.version$