server: 
  port: 9527
 
spring: 
  application:
    name: microservicecloud-zuul-gateway
 
eureka: 
  client: 
    service-url: 
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka  
  instance:
    instance-id: gateway-9527.com
    prefer-ip-address: true

# 配置多个微服务参考 https://blog.csdn.net/u012702547/article/details/78399406
zuul:
  routes:
    mydept.serviceId: microservicecloud-dept
    mydept.path: /mydept/**
  ignored-services: "*"  # 忽略访问的服务, 所有："*"，单个：microservicecloud-dept
  prefix: /gogoo          # 前缀
 
info:
  app.name: gogoo-microservicecloud
  company.name: www.gogoo.com
  build.artifactId: ${project.artifactId}
  build.version: ${project.version}


