server:
  port: 8080

spring:
  application:
    name: weather-demo #服务唯一名字
  http:
    encoding:              #编码格式
      charset: UTF-8
      force: true
      enabled: true
  redis:
    host: 127.0.0.1
    port: 6379
  thymeleaf:
    cache: false #静态文件热部署

# 自定义参数
weather_base_url: http://wthrcdn.etouch.cn/weather_mini?