server:
  port: 13000

spring:
  application:
    name: zuul-gateway #服务唯一名字
  http:
    encoding:              # 编码格式
      charset: UTF-8
      force: true
      enabled: true


eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://182.61.144.28:10500/eureka #客户端注册进eureka服务集群列表内
      #defaultZone: http://eureka7201.com:7201/eureka/,http://eureka7202.com:7202/eureka/,http://eureka7205.com:7205/eureka/  # 集群
  instance:
    instance-id: zuul-gateway-${server.port}   #自定义服务名称信息
    prefer-ip-address: true     #访问路径可以显示IP地址


# 配置多个微服务参考 https://blog.csdn.net/u012702547/article/details/78399406
zuul:
  routes:
    ca:
      serviceId: consumer-api
      path: /ca/**
      sensitiveHeaders: "*"   # 解决经过网关zuul转发请求后发生session失效问题，这是由于zuul默认会丢弃原来的session并生成新的session
  ignored-services: "*"  # 忽略访问的服务, 所有："*"，单个：microservicecloud-dept
  prefix: /gogoo          # 前缀

ribbon: #ribbon负载均衡参数配置
  ReadTimeout: 5000
  ConnectTimeout: 5000

# 微服务基本描述信息
info:
  app.name: zuul-gateway-${server.port}-provider
  company.name: https://www.yaoln.com
  # 调试用
#  build.artifactId: ${project.artifactId}
#  build.version: ${project.version}
 # 打包用
  build.artifactId: $project.artifactId$
  build.version: $project.version$